name: avataaars
description: An avatar generator for anyone to make their beautiful personal avatar easily!
version: 0.5.1
repository: https://github.com/jlnrrg/avataaars

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: <3.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: <3.0.0
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1

flutter:
